export const countrySettings = {
  allCountryDropdown: [
    { en: 'Afghanistan', zh: '阿富汗', flag: '🇦🇫' },
    { en: 'Albania', zh: '阿尔巴尼亚', flag: '🇦🇱' },
    { en: 'Algeria', zh: '阿尔及利亚', flag: '🇩🇿' },
    { en: 'Andorra', zh: '安道尔', flag: '🇦🇩' },
    { en: 'Angola', zh: '安哥拉', flag: '🇦🇴' },
    { en: 'Antigua and Barbuda', zh: '安提瓜和巴布达', flag: '🇦🇬' },
    { en: 'Argentina', zh: '阿根廷', flag: '🇦🇷' },
    { en: 'Armenia', zh: '亚美尼亚', flag: '🇦🇲' },
    { en: 'Australia', zh: '澳大利亚', flag: '🇦🇺' },
    { en: 'Austria', zh: '奥地利', flag: '🇦🇹' },
    { en: 'Azerbaijan', zh: '阿塞拜疆', flag: '🇦🇿' },
    { en: 'Bahamas', zh: '巴哈马', flag: '🇧🇸' },
    { en: 'Bahrain', zh: '巴林', flag: '🇧🇭' },
    { en: 'Bangladesh', zh: '孟加拉国', flag: '🇧🇩' },
    { en: 'Barbados', zh: '巴巴多斯', flag: '🇧🇧' },
    { en: 'Belarus', zh: '白俄罗斯', flag: '🇧🇾' },
    { en: 'Belgium', zh: '比利时', flag: '🇧🇪' },
    { en: 'Belize', zh: '伯利兹', flag: '🇧🇿' },
    { en: 'Benin', zh: '贝宁', flag: '🇧🇯' },
    { en: 'Bhutan', zh: '不丹', flag: '🇧🇹' },
    { en: 'Bolivia', zh: '玻利维亚', flag: '🇧🇴' },
    { en: 'Bosnia and Herzegovina', zh: '波斯尼亚和黑塞哥维那', flag: '🇧🇦' },
    { en: 'Botswana', zh: '博茨瓦纳', flag: '🇧🇼' },
    { en: 'Brazil', zh: '巴西', flag: '🇧🇷' },
    { en: 'Brunei', zh: '文莱', flag: '🇧🇳' },
    { en: 'Bulgaria', zh: '保加利亚', flag: '🇧🇬' },
    { en: 'Burkina Faso', zh: '布基纳法索', flag: '🇧🇫' },
    { en: 'Burundi', zh: '蒲隆地', flag: '🇧🇮' },
    { en: 'Cambodia', zh: '柬埔寨', flag: '🇰🇭' },
    { en: 'Cameroon', zh: '喀麦隆', flag: '🇨🇲' },
    { en: 'Canada', zh: '加拿大', flag: '🇨🇦' },
    { en: 'Cape Verde', zh: '佛得角', flag: '🇨🇻' },
    { en: 'Central African Republic', zh: '中非共和国', flag: '🇨🇫' },
    { en: 'Chad', zh: '乍得', flag: '🇹🇩' },
    { en: 'Chile', zh: '智利', flag: '🇨🇱' },
    { en: 'China', zh: '中国', flag: '🇨🇳' },
    { en: 'Colombia', zh: '哥伦比亚', flag: '🇨🇴' },
    { en: 'Comoros', zh: '科摩罗', flag: '🇰🇲' },
    { en: 'Congo, Democratic Republic of the', zh: '刚果民主共和国', flag: '🇨🇩' },
    { en: 'Congo, Republic of the', zh: '刚果共和国', flag: '🇨🇬' },
    { en: 'Costa Rica', zh: '哥斯达黎加', flag: '🇨🇷' },
    { en: 'Croatia', zh: '克罗地亚', flag: '🇭🇷' },
    { en: 'Cuba', zh: '古巴', flag: '🇨🇺' },
    { en: 'Cyprus', zh: '塞浦路斯', flag: '🇨🇾' },
    { en: 'Czech Republic', zh: '捷克共和国', flag: '🇨🇿' },
    { en: 'Denmark', zh: '丹麦', flag: '🇩🇰' },
    { en: 'Djibouti', zh: '吉布提', flag: '🇩🇯' },
    { en: 'Dominica', zh: '多米尼克', flag: '🇩🇲' },
    { en: 'Dominican Republic', zh: '多米尼加共和国', flag: '🇩🇴' },
    { en: 'East Timor', zh: '东帝汶', flag: '🇹🇱' },
    { en: 'Ecuador', zh: '厄瓜多尔', flag: '🇪🇨' },
    { en: 'Egypt', zh: '埃及', flag: '🇪🇬' },
    { en: 'El Salvador', zh: '萨尔瓦多', flag: '🇸🇻' },
    { en: 'Equatorial Guinea', zh: '赤道几内亚', flag: '🇬🇶' },
    { en: 'Eritrea', zh: '厄立特里亚', flag: '🇪🇷' },
    { en: 'Estonia', zh: '爱沙尼亚', flag: '🇪🇪' },
    { en: 'Ethiopia', zh: '埃塞俄比亚', flag: '🇪🇹' },
    { en: 'Fiji', zh: '斐济', flag: '🇫🇯' },
    { en: 'Finland', zh: '芬兰', flag: '🇫🇮' },
    { en: 'France', zh: '法国', flag: '🇫🇷' },
    { en: 'Gabon', zh: '加蓬', flag: '🇬🇦' },
    { en: 'Gambia', zh: '冈比亚', flag: '🇬🇲' },
    { en: 'Georgia', zh: '格鲁吉亚', flag: '🇬🇪' },
    { en: 'Germany', zh: '德国', flag: '🇩🇪' },
    { en: 'Ghana', zh: '加纳', flag: '🇬🇭' },
    { en: 'Greece', zh: '希腊', flag: '🇬🇷' },
    { en: 'Grenada', zh: '格林纳达', flag: '🇬🇩' },
    { en: 'Guatemala', zh: '危地马拉', flag: '🇬🇹' },
    { en: 'Guinea', zh: '几内亚', flag: '🇬🇳' },
    { en: 'Guinea-Bissau', zh: '几内亚比绍', flag: '🇬🇼' },
    { en: 'Guyana', zh: '圭亚那', flag: '🇬🇾' },
    { en: 'Haiti', zh: '海地', flag: '🇭🇹' },
    { en: 'Honduras', zh: '洪都拉斯', flag: '🇭🇳' },
    { en: 'Hungary', zh: '匈牙利', flag: '🇭🇺' },
    { en: 'Iceland', zh: '冰岛', flag: '🇮🇸' },
    { en: 'India', zh: '印度', flag: '🇮🇳' },
    { en: 'Indonesia', zh: '印度尼西亚', flag: '🇮🇩' },
    { en: 'Iran', zh: '伊朗', flag: '🇮🇷' },
    { en: 'Iraq', zh: '伊拉克', flag: '🇮🇶' },
    { en: 'Ireland', zh: '爱尔兰', flag: '🇮🇪' },
    { en: 'Israel', zh: '以色列', flag: '🇮🇱' },
    { en: 'Italy', zh: '意大利', flag: '🇮🇹' },
    { en: 'Ivory Coast', zh: '科特迪瓦', flag: '🇨🇮' },
    { en: 'Jamaica', zh: '牙买加', flag: '🇯🇲' },
    { en: 'Japan', zh: '日本', flag: '🇯🇵' },
    { en: 'Jordan', zh: '约旦', flag: '🇯🇴' },
    { en: 'Kazakhstan', zh: '哈萨克斯坦', flag: '🇰🇿' },
    { en: 'Kenya', zh: '肯尼亚', flag: '🇰🇪' },
    { en: 'Kiribati', zh: '基里巴斯', flag: '🇰🇮' },
    { en: 'Korea (North)', zh: '北朝鲜', flag: '🇰🇵' },
    { en: 'Korea (South)', zh: '韩国', flag: '🇰🇷' },
    { en: 'Kuwait', zh: '科威特', flag: '🇰🇼' },
    { en: 'Kyrgyzstan', zh: '吉尔吉斯斯坦', flag: '🇰🇬' },
    { en: 'Laos', zh: '老挝', flag: '🇱🇦' },
    { en: 'Latvia', zh: '拉脱维亚', flag: '🇱🇻' },
    { en: 'Lebanon', zh: '黎巴嫩', flag: '🇱🇧' },
    { en: 'Lesotho', zh: '莱索托', flag: '🇱🇸' },
    { en: 'Liberia', zh: '利比里亚', flag: '🇱🇷' },
    { en: 'Libya', zh: '利比亚', flag: '🇱🇾' },
    { en: 'Liechtenstein', zh: '列支敦士登', flag: '🇱🇮' },
    { en: 'Lithuania', zh: '立陶宛', flag: '🇱🇹' },
    { en: 'Luxembourg', zh: '卢森堡', flag: '🇱🇺' },
    { en: 'Madagascar', zh: '马达加斯加', flag: '🇲🇬' },
    { en: 'Malawi', zh: '马拉维', flag: '🇲🇼' },
    { en: 'Malaysia', zh: '马来西亚', flag: '🇲🇾' },
    { en: 'Maldives', zh: '马尔代夫', flag: '🇲🇻' },
    { en: 'Mali', zh: '马里', flag: '🇲🇱' },
    { en: 'Malta', zh: '马耳他', flag: '🇲🇹' },
    { en: 'Marshall Islands', zh: '马绍尔群岛', flag: '🇲🇭' },
    { en: 'Mauritania', zh: '毛里塔尼亚', flag: '🇲🇷' },
    { en: 'Mauritius', zh: '毛里求斯', flag: '🇲🇺' },
    { en: 'Mexico', zh: '墨西哥', flag: '🇲🇽' },
    { en: 'Micronesia', zh: '密克罗尼西亚', flag: '🇫🇲' },
    { en: 'Moldova', zh: '摩尔多瓦', flag: '🇲🇩' },
    { en: 'Monaco', zh: '摩纳哥', flag: '🇲🇨' },
    { en: 'Mongolia', zh: '蒙古', flag: '🇲🇳' },
    { en: 'Montenegro', zh: '黑山', flag: '🇲🇪' },
    { en: 'Morocco', zh: '摩洛哥', flag: '🇲🇦' },
    { en: 'Mozambique', zh: '莫桑比克', flag: '🇲🇿' },
    { en: 'Myanmar', zh: '缅甸', flag: '🇲🇲' },
    { en: 'Namibia', zh: '纳米比亚', flag: '🇳🇦' },
    { en: 'Nauru', zh: '瑙鲁', flag: '🇳🇷' },
    { en: 'Nepal', zh: '尼泊尔', flag: '🇳🇵' },
    { en: 'Netherlands', zh: '荷兰', flag: '🇳🇱' },
    { en: 'New Zealand', zh: '新西兰', flag: '🇳🇿' },
    { en: 'Nicaragua', zh: '尼加拉瓜', flag: '🇳🇮' },
    { en: 'Niger', zh: '尼日尔', flag: '🇳🇪' },
    { en: 'Nigeria', zh: '尼日利亚', flag: '🇳🇬' },
    { en: 'North Macedonia', zh: '北马其顿', flag: '🇲🇰' },
    { en: 'Norway', zh: '挪威', flag: '🇳🇴' },
    { en: 'Oman', zh: '阿曼', flag: '🇴🇲' },
    { en: 'Pakistan', zh: '巴基斯坦', flag: '🇵🇰' },
    { en: 'Palau', zh: '帕劳', flag: '🇵🇼' },
    { en: 'Panama', zh: '巴拿马', flag: '🇵🇦' },
    { en: 'Papua New Guinea', zh: '巴布亚新几内亚', flag: '🇵🇬' },
    { en: 'Paraguay', zh: '巴拉圭', flag: '🇵🇾' },
    { en: 'Peru', zh: '秘鲁', flag: '🇵🇪' },
    { en: 'Philippines', zh: '菲律宾', flag: '🇵🇭' },
    { en: 'Poland', zh: '波兰', flag: '🇵🇱' },
    { en: 'Portugal', zh: '葡萄牙', flag: '🇵🇹' },
    { en: 'Qatar', zh: '卡塔尔', flag: '🇶🇦' },
    { en: 'Romania', zh: '罗马尼亚', flag: '🇷🇴' },
    { en: 'Russia', zh: '俄罗斯', flag: '🇷🇺' },
    { en: 'Rwanda', zh: '卢旺达', flag: '🇷🇼' },
    { en: 'Saint Kitts and Nevis', zh: '圣基茨和尼维斯', flag: '🇰🇳' },
    { en: 'Saint Lucia', zh: '圣卢西亚', flag: '🇱🇨' },
    { en: 'Saint Vincent and the Grenadines', zh: '圣文森特和格林纳丁斯', flag: '🇻🇨' },
    { en: 'Samoa', zh: '萨摩亚', flag: '🇼🇸' },
    { en: 'San Marino', zh: '圣马力诺', flag: '🇸🇲' },
    { en: 'Sao Tome and Principe', zh: '圣多美和普林西比', flag: '🇸🇹' },
    { en: 'Saudi Arabia', zh: '沙特阿拉伯', flag: '🇸🇦' },
    { en: 'Senegal', zh: '塞内加尔', flag: '🇸🇳' },
    { en: 'Serbia', zh: '塞尔维亚', flag: '🇷🇸' },
    { en: 'Seychelles', zh: '塞舌尔', flag: '🇸🇨' },
    { en: 'Sierra Leone', zh: '塞拉利昂', flag: '🇸🇱' },
    { en: 'Singapore', zh: '新加坡', flag: '🇸🇬' },
    { en: 'Slovakia', zh: '斯洛伐克', flag: '🇸🇰' },
    { en: 'Slovenia', zh: '斯洛文尼亚', flag: '🇸🇮' },
    { en: 'Solomon Islands', zh: '所罗门群岛', flag: '🇸🇧' },
    { en: 'Somalia', zh: '索马里', flag: '🇸🇴' },
    { en: 'South Africa', zh: '南非', flag: '🇿🇦' },
    { en: 'South Sudan', zh: '南苏丹', flag: '🇸🇸' },
    { en: 'Spain', zh: '西班牙', flag: '🇪🇸' },
    { en: 'Sri Lanka', zh: '斯里兰卡', flag: '🇱🇰' },
    { en: 'Sudan', zh: '苏丹', flag: '🇸🇩' },
    { en: 'Suriname', zh: '苏里南', flag: '🇸🇷' },
    { en: 'Sweden', zh: '瑞典', flag: '🇸🇪' },
    { en: 'Switzerland', zh: '瑞士', flag: '🇨🇭' },
    { en: 'Syria', zh: '叙利亚', flag: '🇸🇾' },
    { en: 'Taiwan', zh: '台湾', flag: '🇹🇼' },
    { en: 'Tajikistan', zh: '塔吉克斯坦', flag: '🇹🇯' },
    { en: 'Tanzania', zh: '坦桑尼亚', flag: '🇹🇿' },
    { en: 'Thailand', zh: '泰国', flag: '🇹🇭' },
    { en: 'Togo', zh: '多哥', flag: '🇹🇬' },
    { en: 'Tonga', zh: '汤加', flag: '🇹🇴' },
    { en: 'Trinidad and Tobago', zh: '特立尼达和多巴哥', flag: '🇹🇹' },
    { en: 'Tunisia', zh: '突尼斯', flag: '🇹🇳' },
    { en: 'Turkey', zh: '土耳其', flag: '🇹🇷' },
    { en: 'Turkmenistan', zh: '土库曼斯坦', flag: '🇹🇲' },
    { en: 'Tuvalu', zh: '图瓦卢', flag: '🇹🇻' },
    { en: 'Uganda', zh: '乌干达', flag: '🇺🇬' },
    { en: 'Ukraine', zh: '乌克兰', flag: '🇺🇦' },
    { en: 'United Arab Emirates', zh: '阿拉伯联合酋长国', flag: '🇦🇪' },
    { en: 'United Kingdom', zh: '英国', flag: '🇬🇧' },
    { en: 'United States', zh: '美国', flag: '🇺🇸' },
    { en: 'Uruguay', zh: '乌拉圭', flag: '🇺🇾' },
    { en: 'Uzbekistan', zh: '乌兹别克斯坦', flag: '🇺🇿' },
    { en: 'Vanuatu', zh: '瓦努阿图', flag: '🇻🇺' },
    { en: 'Vatican City', zh: '梵蒂冈', flag: '🇻🇦' },
    { en: 'Venezuela', zh: '委内瑞拉', flag: '🇻🇪' },
    { en: 'Vietnam', zh: '越南', flag: '🇻🇳' },
    { en: 'Yemen', zh: '也门', flag: '🇾🇪' },
    { en: 'Zambia', zh: '赞比亚', flag: '🇿🇲' },
    { en: 'Zimbabwe', zh: '津巴布韦', flag: '🇿🇼' },
  ],
};
