import { mergeMap, Observable, Subscription } from 'rxjs';
import { Store } from '@ngxs/store';
import { ToastrService } from 'ngx-toastr';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ProfileState } from '@app/store/states/profile.state';
import { UpdateProfile } from '@app/store/actions/profile.action';
import {
  Component,
  inject,
  OnDestroy,
  OnInit,
  output,
  TemplateRef,
  ViewChild,
} from '@angular/core';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import {
  AutoGenerateIntroduction,
  PatchProfileDetails,
  RegistrationState,
  ViewProfile,
} from '@app/store';
import { CommonService } from '@app/core/services';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { CustomToastComponent } from '../../../../../shared/components/custom-toast/custom-toast.component';

@Component({
  selector: 'app-introduction-dialog',
  standalone: true,
  imports: [FormsModule, CommonModule, TranslatePipe, CustomToastComponent],
  templateUrl: './introduction-dialog.component.html',
  styleUrl: './introduction-dialog.component.scss',
})
export class IntroductionDialogComponent implements OnInit, OnDestroy {
  private _store = inject(Store);
  public introduction: string = '';
  public language: string = 'chinese';
  activeButton: number | null = null;
  public subscriptions: Subscription[] = [];
  public closeDialog = output<Event>({ alias: 'close-dialog' });
  public viewProfile$ = this._store.select(ProfileState.viewProfile);
  public updateProfileSuccessMessage$ = this._store.select(ProfileState.updateProfileSuccessMsg);
  private profileDetails$: Observable<IViewProfile | null> = this._store.select(
    RegistrationState.profileDetails
  );
  public profileData: IViewProfile | null = null;
  private aiIntroduction$: Observable<string | null> = this._store.select(
    RegistrationState.autoGenerateIntroduction
  );

  readonly dialog = inject(MatDialog);
  public warningDialogRef!: MatDialogRef<string, any>;
  @ViewChild('warningDialog') warningDialog!: TemplateRef<string>;

  constructor(
    private _toastr: ToastrService,
    private _translate: TranslateService,
    private _commonService: CommonService
  ) {}

  ngOnInit(): void {
    this.language = this._translate.currentLang === 'zh' ? 'chinese' : 'english';
    this.subscriptions.push(
      this._translate.onLangChange.subscribe(event => {
        this.language = event.lang === 'zh' ? 'chinese' : 'english';
      })
    );
    this.getProfileDataFromStore();
  }

  setActiveButton(buttonNumber: number): void {
    this.activeButton = buttonNumber;
  }

  getProfileDataFromStore() {
    this.subscriptions.push(
      this.profileDetails$.subscribe({
        next: details => {
          if (details) {
            this.profileData = details;
            this.introduction =
              this.language === 'english' ? details.introduction.en : details.introduction.zh;
          }
        },
      })
    );
  }

  onGenerate(type: string, isUpdate = false, event: Event) {
    this._commonService.setMessage(null);
    if (type === 'aiText' && this.introduction === '') {
      this._commonService.setMessage({
        type: 'error',
        message: 'PROFILE_PAGE.INTRODUCTION_REQUIRED',
      });
      return;
    }
    const payload = {
      user_id: this.profileData && this.profileData.unique_id ? this.profileData.unique_id : '',
      description: type === 'aiText' ? this.introduction : '',
      request_type: type === 'aiText' ? 'rephrase' : 'create',
    };
    this.subscriptions.push(
      this._store.dispatch(new AutoGenerateIntroduction(payload)).subscribe({
        next: apiResult => {
          this.getAutoGeneratedData();
          if (isUpdate) {
            this.onSaveIntroduction(event);
          }
        },
        error: apiError => {
          this._toastr.error(apiError.error.response.status.msg, 'Error', {
            closeButton: true,
            timeOut: 3000,
          });
        },
      })
    );
  }
  getAutoGeneratedData() {
    this.subscriptions.push(
      this.aiIntroduction$.subscribe(data => {
        if (data) {
          this.introduction = data;
        }
      })
    );
  }

  onSaveIntroduction(event: Event) {
    const payload = {
      introduction: this.introduction,
    };
    this.subscriptions.push(
      this._store
        .dispatch(new UpdateProfile(payload))
        .pipe(
          mergeMap(() => {
            if (this.profileData) {
              this.language === 'english'
                ? (this.profileData.introduction.en = this.introduction)
                : (this.profileData.introduction.zh = this.introduction);
            }
            return this._store.dispatch(new PatchProfileDetails(this.profileData));
          })
        )
        .subscribe({
          next: () => {
            this.onCloseIntroductionDialog(event);
          },
          error: apiError => {
            this._toastr.error(apiError.error.response.status.msg, 'Error', {
              closeButton: true,
              timeOut: 3000,
            });
          },
        })
    );
  }

  onCloseIntroductionDialog(event: Event) {
    this.closeDialog.emit(event);
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(subscription => subscription.unsubscribe());
  }
}
